<?php

namespace A2\CoreBundle\Repository;

/**
 * ContentRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
