<?php

namespace A2\CoreBundle\Repository;

/**
 * Home4ColumnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Home4ColumnsRepository extends \Doctrine\ORM\EntityRepository
{
}
