<?php

namespace A2\CoreBundle\Repository;

/**
 * Home_4_ColumnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Home_4_ColumnsRepository extends \Doctrine\ORM\EntityRepository
{
}
