a2_core_homepage:
    path:     /
    defaults: { _controller: A2CoreBundle:Home:index }
    
hello_world:
    path:     /hello_world
    defaults: { _controller: A2CoreBundle:Home:index }

a2_core_accueil:
    path:     /accueil
    defaults: { _controller: A2CoreBundle:Home:index }

a2_core_add_file:
    path:     /add_file
    defaults: { _controller: A2CoreBundle:File:addFile }

a2_core_list_file:
    path:     /list_files
    defaults: { _controller: A2CoreBundle:Home:index }

a2_core_categories:
    path:     /ajax/categories/list_with_parent
    defaults: { _controller: A2CoreBundle:Ajax:getListCategoriesInside }

tmp_a2_core_borne:
    path:       /test/borne/accueil
    defaults:   { _controller: A2CoreBundle:Borne:index}

tmp_a2_core_content_test:
    path:       /test/borne/content/{category}
    defaults:
            _controller:  A2CoreBundle:Borne:content
            category:     0

tmp_a2_core_theme_home:
    path:       /test/settings/theme/home
    defaults:   { _controller: A2CoreBundle:Theme:Home4Columns }

tmp_a2_core_theme_content:
    path:       /test/settings/theme/content
    defaults:   { _controller: A2CoreBundle:Theme:ContentRestaurant }

